import React, { useCallback, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const W = 960, H = 540, P = 24;
const rect = (x,y,w,h) => ({x,y,w,h});
const worlds = ['real','shadow'];

// Every level is authored as two simultaneous versions of the same place.
const L = [
 { name:'First Flicker', hint:'A key exists only in the Shadow World. Collect it, then return to reality for the exit.', shifts:9,
   real:{plats:[rect(0,500,960,40),rect(90,410,190,20),rect(580,405,140,20)], keys:[], doors:[], switches:[], traps:[], enemies:[]},
   shadow:{plats:[rect(0,500,960,40),rect(300,430,130,20),rect(505,360,150,20),rect(725,420,110,20)], keys:[rect(565,325,18,24)], doors:[], switches:[], traps:[], enemies:[]}, exit:rect(875,440,38,60), start:{x:50,y:450}},
 { name:'Echo Lock', hint:'Step on the violet pressure plate to open the matching door in the other world.', shifts:10,
   real:{plats:[rect(0,500,960,40),rect(120,420,170,20),rect(680,400,150,20)],keys:[],doors:[{...rect(745,320,24,180),id:'a'}],switches:[],traps:[],enemies:[]},
   shadow:{plats:[rect(0,500,960,40),rect(335,430,150,20),rect(535,365,130,20),rect(715,300,165,20)],keys:[rect(580,330,18,24)],doors:[],switches:[{...rect(760,280,42,20),id:'a'}],traps:[],enemies:[]}, exit:rect(890,440,38,60), start:{x:52,y:450}},
 { name:'Thin Places', hint:'You only have six shifts. Use the shadow ledges as a bridge, then find the key.', shifts:6,
   real:{plats:[rect(0,500,960,40),rect(70,420,120,20),rect(720,390,170,20)],keys:[],doors:[],switches:[],traps:[],enemies:[]},
   shadow:{plats:[rect(0,500,960,40),rect(230,440,90,20),rect(385,375,90,20),rect(540,320,100,20),rect(690,370,150,20)],keys:[rect(585,285,18,24)],doors:[],switches:[],traps:[],enemies:[]}, exit:rect(890,440,38,60), start:{x:48,y:450}},
 { name:'Dark Pursuit', hint:'Avoid red spikes and the wandering wraith. A shadow switch opens reality’s final gate.', shifts:9,
   real:{plats:[rect(0,500,960,40),rect(125,410,125,20),rect(460,390,150,20),rect(710,420,120,20)],keys:[],doors:[{...rect(845,320,24,180),id:'b'}],switches:[],traps:[rect(280,480,80,20),rect(630,480,65,20)],enemies:[{x:490,y:356,w:26,h:34,min:465,max:580,v:1.35}]},
   shadow:{plats:[rect(0,500,960,40),rect(280,430,150,20),rect(520,340,145,20),rect(730,300,130,20)],keys:[rect(775,265,18,24)],doors:[],switches:[{...rect(780,280,42,20),id:'b'}],traps:[rect(440,480,68,20)],enemies:[]}, exit:rect(900,440,38,60), start:{x:50,y:450}},
 { name:'The Last Divide', hint:'All lessons combine: plate, key, wraith and a narrow shift budget. Escape both worlds.', shifts:8,
   real:{plats:[rect(0,500,960,40),rect(95,420,125,20),rect(365,385,105,20),rect(665,395,115,20)],keys:[],doors:[{...rect(835,320,24,180),id:'c'}],switches:[],traps:[rect(235,480,90,20),rect(540,480,85,20)],enemies:[{x:680,y:361,w:26,h:34,min:665,max:755,v:1.6}]},
   shadow:{plats:[rect(0,500,960,40),rect(260,435,90,20),rect(410,360,100,20),rect(565,295,120,20),rect(745,340,115,20)],keys:[rect(610,260,18,24)],doors:[],switches:[{...rect(775,320,42,20),id:'c'}],traps:[rect(365,480,68,20)],enemies:[{x:440,y:326,w:26,h:34,min:415,max:485,v:1.15}]}, exit:rect(895,440,38,60), start:{x:48,y:450}}
];
const hit = (a,b) => a.x < b.x+b.w && a.x+a.w > b.x && a.y < b.y+b.h && a.y+a.h > b.y;
const clamp = (n,a,b)=>Math.max(a,Math.min(b,n));

function loadProgress(){ try{return JSON.parse(localStorage.getItem('shadow-switch-progress')) || {unlocked:1,best:0}}catch{return {unlocked:1,best:0}} }

function App(){
 const canvas = useRef(null), keys = useRef({}), game = useRef(null), raf=useRef();
 const [screen,setScreen]=useState('menu'), [level,setLevel]=useState(0), [hud,setHud]=useState({score:0,lives:3,shifts:0,world:'real',time:0,keys:0});
 const [progress,setProgress]=useState(loadProgress), [message,setMessage]=useState('');
 const save = useCallback(p=>{setProgress(p);localStorage.setItem('shadow-switch-progress',JSON.stringify(p))},[]);
 const begin = useCallback((n=0)=>{ const d=L[n], p={x:d.start.x,y:d.start.y,w:P,h:34,vx:0,vy:0,onGround:false}; game.current={n, p, world:'real', shifts:d.shifts, lives:3, score:0, started:performance.now(), paused:false, won:false, key:false, opened:{}, collect:new Set(), enemies: worlds.reduce((a,w)=>{a[w]=(d[w].enemies||[]).map(e=>({...e}));return a},{}), flash:0}; setLevel(n);setScreen('play');setMessage(d.hint);setHud({score:0,lives:3,shifts:d.shifts,world:'real',time:0,keys:0}); },[]);
 const reset = useCallback(()=>begin(level),[begin,level]);
 const togglePause=useCallback(()=>{if(game.current){game.current.paused=!game.current.paused;setScreen(game.current.paused?'pause':'play')}},[]);
 const shift=useCallback(()=>{let g=game.current;if(!g||g.paused||g.won)return;if(g.shifts<=0){setMessage('No shadow energy left!');return}g.world=g.world==='real'?'shadow':'real';g.shifts--;g.flash=20;setHud(h=>({...h,world:g.world,shifts:g.shifts}));},[]);
 const die=useCallback(()=>{const g=game.current;if(!g||g.flash>0)return;g.lives--;g.flash=55;if(g.lives<=0){setHud(h=>({...h,lives:0}));setScreen('lose');return}const s=L[g.n].start;Object.assign(g.p,{x:s.x,y:s.y,vx:0,vy:0});setMessage('The worlds push you back.');setHud(h=>({...h,lives:g.lives}));},[]);
 useEffect(()=>{const down=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','w','a','s','d','W','A','S','D','p','P'].includes(e.key))e.preventDefault();if(e.key===' ')shift();if(e.key.toLowerCase()==='p')togglePause();keys.current[e.key.toLowerCase()]=true};const up=e=>keys.current[e.key.toLowerCase()]=false;window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}},[shift,togglePause]);
 useEffect(()=>{let last=performance.now();const loop=t=>{const c=canvas.current,g=game.current;if(c){const ctx=c.getContext('2d'), dpr=devicePixelRatio||1;if(c.width!==W*dpr){c.width=W*dpr;c.height=H*dpr;ctx.scale(dpr,dpr)} const dt=Math.min(2,(t-last)/16.67);last=t;if(g&&!g.paused&&!g.won){const d=L[g.n], w=d[g.world], p=g.p, inp=keys.current;const left=inp.a||inp.arrowleft,right=inp.d||inp.arrowright,jump=inp.w||inp.arrowup; p.vx+=(right?0.85:0)-(left?0.85:0);p.vx*=0.78;p.vx=clamp(p.vx,-6,6);if(jump&&p.onGround){p.vy=-12;p.onGround=false}p.vy+=0.7*dt;p.vy=Math.min(p.vy,15);p.x+=p.vx*dt; let solids=[...w.plats,...w.doors.filter(o=>!g.opened[o.id])];for(const s of solids)if(hit(p,s)){if(p.vx>0)p.x=s.x-p.w;else if(p.vx<0)p.x=s.x+s.w;p.vx=0}p.y+=p.vy*dt;p.onGround=false;for(const s of solids)if(hit(p,s)){if(p.vy>0){p.y=s.y-p.h;p.onGround=true}else if(p.vy<0)p.y=s.y+s.h;p.vy=0}p.x=clamp(p.x,0,W-p.w);if(p.y>H+80)die(); for(const sw of w.switches)if(hit(p,sw)){g.opened[sw.id]=true;setMessage('The linked gate dissolves.')}for(let i=0;i<w.keys.length;i++){const k=w.keys[i];if(!g.collect.has(g.world+i)&&hit(p,k)){g.collect.add(g.world+i);g.key=true;g.score+=100;setMessage('Shadow key acquired.');}}for(const tr of w.traps)if(hit(p,{...tr,y:tr.y+4,h:tr.h}))die();for(const e of g.enemies[g.world]){e.x+=e.v*dt;if(e.x<e.min||e.x>e.max){e.v*=-1;e.x=clamp(e.x,e.min,e.max)}if(hit(p,e))die()}if(g.world==='real'&&g.key&&hit(p,d.exit)){g.won=true;const next=Math.min(5,Math.max(progress.unlocked,g.n+2));save({...progress,unlocked:next,best:Math.max(progress.best,g.score+Math.floor((t-g.started)/100))});setScreen(g.n===4?'complete':'win')}if(g.flash>0)g.flash-=dt;setHud({score:g.score,lives:g.lives,shifts:g.shifts,world:g.world,time:Math.floor((t-g.started)/1000),keys:g.key?1:0});}
  ctx.setTransform(dpr,0,0,dpr,0,0); draw(ctx,g); }raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf.current)},[die,progress,save]);
 const touch=(key,val)=>{keys.current[key]=val};
 return <main><header><div className="brand"><span>SHADOW</span> SWITCH</div><div className="tag">DIMENSIONAL PLATFORMER</div></header>
 <section className="game-shell"><canvas ref={canvas} aria-label="Shadow Switch game canvas"/><div className="hud"><div><b>LEVEL {level+1}</b><small>{L[level].name}</small></div><div className="stat">◆ {hud.keys}/1</div><div className="stat">◈ {hud.shifts}</div><div className="stat">♥ {hud.lives}</div><div className="stat timer">{String(Math.floor(hud.time/60)).padStart(2,'0')}:{String(hud.time%60).padStart(2,'0')}</div><button onClick={togglePause} aria-label="Pause">Ⅱ</button></div>
 {screen!=='play'&&<div className={`overlay ${screen==='help'?'help-overlay':''}`}>{screen==='menu'&&<><p className="eyebrow">TWO WORLDS. ONE WAY OUT.</p><h1>SHADOW<br/><em>SWITCH</em></h1><p>Reality is solid. Shadows reveal paths unseen.</p><button className="primary" onClick={()=>begin(0)}>Start adventure</button><button onClick={()=>setScreen('help')}>Help / How to Play</button><div className="level-select">{L.map((x,i)=><button key={x.name} disabled={i>=progress.unlocked} onClick={()=>begin(i)}>{i+1}<small>{i<progress.unlocked?x.name:'LOCKED'}</small></button>)}</div><p className="keys-help">MOVE <b>WASD / ARROWS</b> &nbsp; · &nbsp; SWITCH <b>SPACE</b> &nbsp; · &nbsp; PAUSE <b>P</b></p></>}{screen==='help'&&<><p className="eyebrow">FIELD GUIDE // SHADOW SWITCH</p><h2>How to play</h2><div className="help-grid"><article><b>◇ OBJECTIVE</b><p>Collect the Shadow Key, unlock the path, and enter the glowing exit in the Real World.</p></article><article><b>⌨ MOVE &amp; JUMP</b><p>Use <strong>WASD</strong> or the <strong>Arrow Keys</strong>. W / ↑ jumps; A-D / ←-→ move.</p></article><article><b>◈ SWITCH WORLDS</b><p>Press <strong>Space</strong> to swap between Real and Shadow. Each world has different platforms and paths.</p></article><article><b>⚠ STAY ALIVE</b><p>Avoid spikes and roaming wraiths. Falling or touching a hazard costs one life.</p></article><article><b>◆ KEYS &amp; PLATES</b><p>Pick up gold keys. Stand on violet pressure plates to dissolve their matching gates.</p></article><article><b>◎ PLAN YOUR SHIFTS</b><p>Shifts are limited per level. Watch the ◈ counter and only switch when it opens a route or keeps you safe.</p></article><article><b>▣ RUN STATUS</b><p>♥ shows lives; ◆ shows keys; the timer tracks your run. Earn score by collecting keys and finishing quickly.</p></article><article><b>Ⅱ PAUSE &amp; RETRY</b><p>Press <strong>P</strong> or the pause button to resume, restart the level, or return to level select.</p></article></div><button className="primary" onClick={()=>setScreen('menu')}>Back to Game</button></>}{screen==='pause'&&<><p className="eyebrow">TIME STOPS BETWEEN WORLDS</p><h2>Paused</h2><button className="primary" onClick={togglePause}>Resume</button><button onClick={reset}>Restart level</button><button onClick={()=>setScreen('menu')}>Level select</button></>}{screen==='lose'&&<><p className="eyebrow">THE SHADOWS CONSUMED YOU</p><h2>Out of lives</h2><button className="primary" onClick={reset}>Try again</button><button onClick={()=>setScreen('menu')}>Level select</button></>}{(screen==='win'||screen==='complete')&&<><p className="eyebrow">ESCAPE COMPLETE</p><h2>{screen==='complete'?'You crossed the divide':'Level complete'}</h2><p>{screen==='complete'?'All five rifts are sealed. You are free.':'A new breach has opened ahead.'}</p>{screen==='win'&&<button className="primary" onClick={()=>begin(level+1)}>Next level</button>}<button onClick={()=>setScreen('menu')}>Level select</button></>}</div>}
 <div className="tip">{message}</div></section>
 <section className="mobile-controls"><div className="dpad"><button onPointerDown={()=>touch('a',true)} onPointerUp={()=>touch('a',false)} onPointerLeave={()=>touch('a',false)}>←</button><button onPointerDown={()=>touch('d',true)} onPointerUp={()=>touch('d',false)} onPointerLeave={()=>touch('d',false)}>→</button></div><div><button className="jump" onPointerDown={()=>touch('w',true)} onPointerUp={()=>touch('w',false)}>↑</button><button className="switch" onClick={shift}>◇</button></div></section>
 <footer><span>REAL WORLD <i className="real-dot"/></span><span>SHADOW WORLD <i className="shadow-dot"/></span><button onClick={()=>{save({unlocked:1,best:0});setMessage('Progress reset.')}}>Reset saved progress</button></footer></main>
}
function draw(ctx,g){const shadow=g?.world==='shadow';const grad=ctx.createLinearGradient(0,0,W,H);grad.addColorStop(0,shadow?'#170d35':'#082f43');grad.addColorStop(1,shadow?'#05030f':'#12324a');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);ctx.globalAlpha=.16;ctx.strokeStyle=shadow?'#b43cff':'#73e5e5';for(let x=-H;x<W;x+=55){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+H,H);ctx.stroke()}ctx.globalAlpha=1;if(!g)return;const d=L[g.n],w=d[g.world];for(const p of w.plats){ctx.fillStyle=shadow?'#38205e':'#24546a';ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle=shadow?'#9d58de':'#71d3d0';ctx.fillRect(p.x,p.y,p.w,4)}for(const door of w.doors)if(!g.opened[door.id]){ctx.fillStyle='#b761e7';ctx.fillRect(door.x,door.y,door.w,door.h);ctx.fillStyle='#f0adff';for(let y=door.y+10;y<door.y+door.h;y+=20)ctx.fillRect(door.x+5,y,14,4)}for(const sw of w.switches){ctx.fillStyle='#d580ff';ctx.fillRect(sw.x,sw.y,sw.w,sw.h);ctx.fillStyle='#fff';ctx.fillRect(sw.x+8,sw.y+6,sw.w-16,5)}for(let i=0;i<w.keys.length;i++)if(!g.collect.has(g.world+i)){const k=w.keys[i];ctx.fillStyle='#ffe277';ctx.fillRect(k.x+7,k.y,6,21);ctx.beginPath();ctx.arc(k.x+10,k.y+5,7,0,Math.PI*2);ctx.strokeStyle='#ffe277';ctx.lineWidth=4;ctx.stroke()}for(const tr of w.traps){ctx.fillStyle='#ff4e63';for(let x=tr.x;x<tr.x+tr.w;x+=16){ctx.beginPath();ctx.moveTo(x,tr.y+tr.h);ctx.lineTo(x+8,tr.y);ctx.lineTo(x+16,tr.y+tr.h);ctx.fill()}}for(const e of g.enemies[g.world]){ctx.fillStyle='#ef4e87';ctx.beginPath();ctx.arc(e.x+13,e.y+15,14,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(e.x+7,e.y+11,4,4);ctx.fillRect(e.x+16,e.y+11,4,4)}if(g.world==='real'){ctx.strokeStyle='#73ffd8';ctx.lineWidth=3;ctx.strokeRect(d.exit.x,d.exit.y,d.exit.w,d.exit.h);ctx.fillStyle='#73ffd8';ctx.fillText('EXIT',d.exit.x-3,d.exit.y-8)}const p=g.p;ctx.save();ctx.globalAlpha=g.flash>0?.5+Math.sin(g.flash)*.3:1;ctx.fillStyle=shadow?'#dca8ff':'#f5f8e7';ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle=shadow?'#7d35bf':'#14364b';ctx.fillRect(p.x+5,p.y+8,4,4);ctx.fillRect(p.x+15,p.y+8,4,4);ctx.restore();if(g.flash>0){ctx.fillStyle=shadow?'rgba(177,56,255,.16)':'rgba(80,240,230,.12)';ctx.fillRect(0,0,W,H)}}
createRoot(document.getElementById('root')).render(<App/>);
